name: NodeJS with Webpack

on:
  push:
    branches: [ "9zx-Sanka" ]
  pull_request:
    branches: [ "9zx-Sanka" ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npx webpack
